apiVersion: v1
kind: Service
metadata:
  name: express-service
  namespace: apps
  labels:
    app: express-app
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: express-app
