apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-controller
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create', 'patch']
  - apiGroups: ['external-secrets.io']
    resources: ['secretstores', 'clustersecretstores', 'externalsecrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['external-secrets.io']
    resources: ['externalsecrets', 'secretstores', 'clustersecretstores']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['external-secrets.io']
    resources: ['externalsecrets/status', 'secretstores/status', 'clustersecretstores/status']
    verbs: ['get', 'patch', 'update']
  - apiGroups: ['coordination.k8s.io']
    resources: ['leases']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-controller
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-webhook
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['external-secrets.io']
    resources: ['secretstores', 'clustersecretstores', 'externalsecrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['admissionregistration.k8s.io']
    resources: ['validatingadmissionconfigurations']
    verbs: ['get', 'list', 'patch', 'update', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-webhook
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets-system
