export const NOT_LOGGED_IN = 'You are not logged in! Please log in to get access.';
export const TOKEN_INVALID_FOR_IP = 'Token is not valid for this IP address.';
export const USER_NO_LONGER_EXISTS = 'The user belonging to this token no longer exists.';
export const USER_CHANGED_PASSWORD = 'User recently changed password! Please log in again.';
export const NO_PERMISSION = 'You do not have permission to perform this action';
export const GOOGLE_OAUTH_SIGNUP_SUCCESS = 'Google OAuth signup successful';
export const GOOGLE_OAUTH_LOGIN_SUCCESS = 'Google OAuth login successful';
export const SUCCESS = 'The operation has been successful';
export const SOMETHING_WENT_WRONG = 'Something went wrong!';
export const NOT_FOUND = (entity) => `${entity} not found`;
export const TOO_MANY_REQUESTS = 'Too many requests! Please try again after some time';
export const ALREADY_EXIST = (entity, identifier) => `${entity} already exist with ${identifier}`;
export const INVALID_PHONE_NUMBER = `Invalid phone number`;
export const INVALID_TIMEZONE = `Invalid timezone`;
export const INVALID_EMAIL = `Invalid email address`;
export const INVALID_PASSWORD = `Invalid password`;
export const INVALID_ACCOUNT_CONFIRMATION_EMAIL_OR_CODE = `Invalid account confirmation token or code`;
export const ACCOUNT_ALREADY_CONFIRMED = `Account already confirmed`;
export const INVALID_EMAIL_OR_PASSWORD = `Invalid email address or password`;
export const UNAUTHORIZED = `You are not authorized to perform this action`;
export const ACCOUNT_CONFIRMATION_REQUIRED = `Account Confirmation Required`;
export const EXPIRED_URL = `Your password reset url is expired`;
export const INVALID_REQUEST = `Invalid request`;
export const INVALID_OLD_PASSWORD = `Invalid old password`;
export const PASSWORD_MATCHING_WITH_OLD_PASSWORD = `Password matching with old password`;
