# Apps Namespace Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    tier: application
    istio-injection: enabled
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: 'workload-type=application'
---
# Resource Quota for Apps Namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: apps-resource-quota
  namespace: apps
spec:
  hard:
    requests.cpu: '10'
    requests.memory: 20Gi
    limits.cpu: '20'
    limits.memory: 40Gi
    persistentvolumeclaims: '10'
    pods: '50'
    services: '20'
    secrets: '50'
    configmaps: '50'
---
# Limit Range for Apps Namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: apps-limit-range
  namespace: apps
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 500Mi
      type: Container
    - max:
        cpu: 2000m
        memory: 4Gi
        ephemeral-storage: 5Gi
      min:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 100Mi
      type: Container
