apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    tier: infrastructure
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    name: infrastructure
    tier: platform
    monitoring: enabled
